name: Tests

on:
  repository_dispatch:
    types: [build_complete]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  run_tests:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-18.04
    
    name: Run Tests

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: build-tarball
        path: ${{runner.workspace}}
        
    - name: Extract tarball
      run: tar -xvf build.tar ${{runnner.workspace}}/build
  
    - name: Set BOOST_ROOT
      run: echo "::set-env name=BOOST_ROOT::$BOOST_ROOT_1_72_0"

    - name: Set LD_LIBRARY_PATH
      run: echo "::set-env name=LD_LIBRARY_PATH::$BOOST_ROOT/lib"

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE --verbose
